spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/club?erverTimezone=CST
    username: root
    password: 123456
  data:
    resources:
      static-locations: classpath:static/
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080


upload:
  location:
    os: E:/BistuMaker/web/club_demo-master/backend/target/classes/static/images
    os1: E:/BistuMaker/web/club_demo-master/backend/target/classes/static

#你把这个目录改下就可以了
#改成你的本地目录

